In [7]:
x = 1
y = 2
z = x + y
z

3

# 잼잼
## 뭐라는거야

수식은 $alpha$

In [1]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
y =  np.arange(10, 50)


In [4]:
y[10:20:2]

array([20, 22, 24, 26, 28])

In [5]:
y[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [6]:
x = np.arange(9).reshape((3,3))

In [7]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
k = [ i in range(9)]

NameError: name 'i' is not defined

In [9]:
a = np.array([1, 2, 0, 0, 4, 0])

In [10]:
b = a[ a != 0]

In [11]:
b

array([1, 2, 4])

In [49]:
k = [ i for i in range(9)]
k

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [14]:
np.eye(3)


array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [23]:
l = np.random.rand(3, 3)
l

array([[ 0.38447461,  0.97106565,  0.03623739],
       [ 0.92022965,  0.91903539,  0.10631734],
       [ 0.37772847,  0.92501418,  0.28583176]])

In [24]:
l.max(axis=1)

array([ 0.97106565,  0.92022965,  0.92501418])

In [25]:
l.max(axis=0)

array([ 0.92022965,  0.97106565,  0.28583176])

In [28]:
l.mean(axis=1)

array([ 0.46392588,  0.64852746,  0.5295248 ])

In [29]:
l.mean(axis=0)

array([ 0.56081091,  0.93837174,  0.1427955 ])

In [30]:
%%timeit
y = [i*2 for i in range(10000)]

1000 loops, best of 3: 579 µs per loop


In [31]:
import datetime


In [34]:
dt = datetime.datetime.now()

In [35]:
dt

datetime.datetime(2016, 7, 7, 10, 40, 57, 788983)

In [36]:
dt.year

2016

In [37]:
dt.month

7

In [38]:
dt.date

<function date>

In [39]:
dt.day

7

In [40]:
dt.hour

10

In [41]:
dt.minute

40

In [42]:
dt.second

57

In [47]:
dt.microsecond

788983

In [44]:
dt.weekday()

3

In [50]:
dt.toordinal()

736152

In [51]:
dt.strftime("%Y-%m-%d %H:%M")

'2016-07-07 10:40'

In [54]:
dt.strftime("%B %d %A, %H, %M")

'July 07 Thursday, 10, 40'

In [55]:
dt.strftime(u"%Y년 %m월 %d일 %H시 %M분 %S초".encode("utf-8"))

'2016\xeb\x85\x84 07\xec\x9b\x94 07\xec\x9d\xbc 10\xec\x8b\x9c 40\xeb\xb6\x84 57\xec\xb4\x88'

In [57]:
dt1 = datetime.datetime(2016, 2, 19, 14)
dt2 = datetime.datetime(2016, 1, 2, 13)
td = dt1 - dt2
td

datetime.timedelta(48, 3600)

In [59]:
td.total_seconds()

4150800.0

In [60]:
import time
print("start...")
time.sleep(1)
print(1)
time.sleep(1)
print(2)
time.sleep(1)
print(3)
time.sleep(1)
print(4)
time.sleep(1)
print("finish!")

start...
1
2
3
4
finish!


In [61]:


import pytz
seoul = pytz.timezone("Asia/Seoul")

In [62]:
dt = dt.replace(tzinfo=pytz.utc)
dt

datetime.datetime(2016, 7, 7, 10, 40, 57, 788983, tzinfo=<UTC>)

In [63]:
dt.astimezone(seoul)

datetime.datetime(2016, 7, 7, 19, 40, 57, 788983, tzinfo=<DstTzInfo 'Asia/Seoul' KST+9:00:00 STD>)

In [64]:
dt = datetime.datetime.now()

In [65]:
dt

datetime.datetime(2016, 7, 7, 11, 2, 32, 814361)

In [66]:
dt.astimezone(seoul)

ValueError: astimezone() cannot be applied to a naive datetime

In [68]:
from dateutil.parser import parse

In [69]:
parse("2016-04-16")

datetime.datetime(2016, 4, 16, 0, 0)

In [70]:
s = pd.Series([4, 7, -5, 3])
s

0    4
1    7
2   -5
3    3
dtype: int64

In [71]:
s.values

array([ 4,  7, -5,  3])

In [73]:
s.shape

(4,)

In [75]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [76]:
np.exp(s)

0      54.598150
1    1096.633158
2       0.006738
3      20.085537
dtype: float64

In [77]:
s

0    4
1    7
2   -5
3    3
dtype: int64

In [78]:
s2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
s2

d    4
b    7
a   -5
c    3
dtype: int64

In [79]:
s2.index

Index([u'd', u'b', u'a', u'c'], dtype='object')

In [80]:
s2.values

array([ 4,  7, -5,  3])

In [82]:
s2['a']

-5

In [83]:
s2['d':'a']

d    4
b    7
a   -5
dtype: int64

In [84]:
s2[['a', 'b']]

a   -5
b    7
dtype: int64

In [85]:
s2[0]

4

In [86]:
s2[:1]

d    4
dtype: int64

In [87]:
s[:1]

0    4
dtype: int64

In [88]:
sdata = {'Ohio':3500, 'Oregon':2000}
s3 = pd.Series(sdata)
s3

Ohio      3500
Oregon    2000
dtype: int64

In [89]:
s4 = pd.Series({'A':'a', 'B':'b'}, index=['A', 'B', 'C'])

In [90]:
s4

A      a
B      b
C    NaN
dtype: object

In [92]:
s4.isnull()

A    False
B    False
C     True
dtype: bool

In [93]:
s4.name= "Cap"

In [94]:
s4

A      a
B      b
C    NaN
Name: Cap, dtype: object

In [95]:
s4

A      a
B      b
C    NaN
Name: Cap, dtype: object

In [96]:
s4.name = 'Cap'

In [97]:
s4

A      a
B      b
C    NaN
Name: Cap, dtype: object

In [98]:
s4.index.name = 'lower'

In [99]:
s4

lower
A      a
B      b
C    NaN
Name: Cap, dtype: object

In [102]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9]
}
df = pd.DataFrame(data, columns=['state', 'year', 'pop'])
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [105]:
type(df)


pandas.core.frame.DataFrame

In [106]:
df2 = pd.DataFrame(data, 
                   columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [107]:
df['state']

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

In [108]:
df['pop']

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
Name: pop, dtype: float64

In [109]:
df[:2]

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [110]:
df2[:2]

year state  pop debt
one  2000  Ohio  1.5  NaN
two  2001  Ohio  1.7  NaN

In [111]:
df2['one']

KeyError: 'one'

In [112]:
df2[one]

NameError: name 'one' is not defined

In [115]:
df2['debt'] = np.arange(5)

In [116]:
df2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [117]:
df2['easter'] = df2.state == 'Ohio'

In [118]:
df2

year   state  pop  debt easter
one    2000    Ohio  1.5     0   True
two    2001    Ohio  1.7     1   True
three  2002    Ohio  3.6     2   True
four   2001  Nevada  2.4     3  False
five   2002  Nevada  2.9     4  False

In [119]:
del df2['easter']

In [120]:
df2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [121]:
df.state #Series  로 됨

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
Name: state, dtype: object

In [123]:
df[['state']] # DataFrame  으로 남음

state
0    Ohio
1    Ohio
2    Ohio
3  Nevada
4  Nevada

In [127]:
df2[['state', 'pop']][1:3]

state  pop
two    Ohio  1.7
three  Ohio  3.6

In [128]:
df2.ix[1:3, ['state', 'pop']]

state  pop
two    Ohio  1.7
three  Ohio  3.6

In [130]:
df2.sort_index()

year   state  pop  debt
five   2002  Nevada  2.9     4
four   2001  Nevada  2.4     3
one    2000    Ohio  1.5     0
three  2002    Ohio  3.6     2
two    2001    Ohio  1.7     1

In [131]:
df3 = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])
df3

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [135]:
df3.sort_values('d', ascending=False)

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [134]:
df3.sort_values?


In [139]:
s = pd.Series([5, 4, 6, -1, -1])

In [140]:
s.rank(method='min')

0    4.0
1    3.0
2    5.0
3    1.0
4    1.0
dtype: float64

In [145]:
s = pd.Series(np.random.randn(10), index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd', 'd'], [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])
s

a  1    0.713451
   2    1.499869
   3   -0.407768
b  1    1.033290
   2   -2.666198
c  3    0.144314
   1   -0.802235
d  2   -1.007777
   2    0.301448
   3    1.015394
dtype: float64

In [149]:
df6 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'd', 'c' ], data1: range(6)})

NameError: name 'data1' is not defined

In [ ]:
pd.merge(df4, df5)

In [ ]:
#how = inner, outer, left, right

In [ ]:
pd.concat([s1, s2, s3])